#!/bin/bash
# Build "10K AI.app" into /Applications. Re-run this if the project moves —
# the launcher hardcodes absolute paths, because an app started from the Dock
# gets none of your shell profile and so has no useful PATH.
#
#   ./make_app.sh
#
# The app is a launcher, not a copy: it starts serve.py out of this directory
# and hands the URL to your browser. Nothing is duplicated, so editing the site
# here changes the app immediately.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
APP="/Applications/10K AI.app"
PORT=4321

# Baked in at build time, not read at run time: LaunchServices starts a
# script-based bundle as x86_64 under Rosetta, and inside that process
# `uname -m` answers x86_64 too, so the launcher cannot detect its way out.
# The translated python then can't dlopen numpy's arm64 .so and every
# extraction dies with a numpy import error that says nothing about
# architecture. This shell is native, so ask it.
NATIVE_ARCH="$(uname -m)"

echo "building icon"
(cd "$ROOT/site/assets" && python3 make_icon.py)

mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$ROOT/site/assets/app.icns" "$APP/Contents/Resources/app.icns"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key>            <string>10K AI</string>
  <key>CFBundleDisplayName</key>     <string>10K AI</string>
  <key>CFBundleIdentifier</key>      <string>local.darren.tenk-ai</string>
  <key>CFBundleVersion</key>         <string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundlePackageType</key>     <string>APPL</string>
  <key>CFBundleExecutable</key>      <string>10K AI</string>
  <key>CFBundleIconFile</key>        <string>app</string>
  <key>LSMinimumSystemVersion</key>  <string>11.0</string>
  <!-- no window of its own: it starts the server and hands off to the browser -->
  <key>LSUIElement</key>             <true/>
  <key>LSBackgroundOnly</key>        <false/>
</dict>
</plist>
PLIST

cat > "$APP/Contents/MacOS/10K AI" <<LAUNCHER
#!/bin/sh
# Start the server if it isn't already up, then open the site.
# Generated by make_app.sh — edit that, not this.
#
# /usr/bin/python3 is the interpreter with pandas and lxml on this machine, and
# it's also what run_10k.sh resolves to from a bare PATH, so the browser and the
# terminal run the same code. It is started through \`arch\` because
# LaunchServices otherwise runs this bundle translated — see make_app.sh.

ROOT="$ROOT"
ARCH="$NATIVE_ARCH"
URL="http://localhost:$PORT/"
LOG="\$HOME/Library/Logs/10K AI.log"

up() { /usr/bin/curl -fsS -o /dev/null -m 2 "\$URL"; }

if ! up; then
  mkdir -p "\$(dirname "\$LOG")"
  cd "\$ROOT" || exit 1
  # detached: the server outlives this launcher, which exits as soon as the
  # browser has the page
  nohup /usr/bin/arch -"\$ARCH" /usr/bin/python3 serve.py >>"\$LOG" 2>&1 &

  i=0
  while [ \$i -lt 60 ]; do
    up && break
    /bin/sleep 0.25
    i=\$((i + 1))
  done

  if ! up; then
    /usr/bin/osascript -e 'display alert "10K AI could not start" message "The server did not come up. Check ~/Library/Logs/10K AI.log." as critical'
    exit 1
  fi
fi

/usr/bin/open "\$URL"
LAUNCHER

chmod +x "$APP/Contents/MacOS/10K AI"
touch "$APP"
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f "$APP"

echo "built $APP  ->  $ROOT"
